#!/sbin/sh

GETPROP="/sbin/getprop"

um
if [ $? != "0" ]; then
	echo "Unable to unmount!"
	exit 1
fi


case $1 in
    repair)
	if [ -e `$GETPROP ro.sd-ext.block` ]; then

		e2fsck -yf `$GETPROP ro.sd-ext.block`
	else
		echo "No ext partition found!"
		exit 1
	fi
	exit 0
        ;;
    ext3)
	if [ -e `$GETPROP ro.sd-ext.block` ]; then

		e2fsck -yf `$GETPROP ro.sd-ext.block`
		tune2fs -c0 -i0 -j `$GETPROP ro.sd-ext.block`
	else
		echo "No ext partition found!"
		exit 1
	fi
	exit 0
	;;
    ext4)
	if [ -e `$GETPROP ro.sd-ext.block` ]; then

		tune2fs -O extents,uninit_bg,dir_index `$GETPROP ro.sd-ext.block`
		e2fsck -fpDC0 `$GETPROP ro.sd-ext.block`
	else
		echo "No ext partition found!"
		exit 1
	fi
	exit 0
        ;;
    --)
	exit 0
        ;;
esac
