#!/sbin/sh

GETPROP="/sbin/getprop"

um
if [ $? != "0" ]; then
	echo "Unable to unmount!"
	exit 1
fi


if [ -e `$GETPROP ro.sdcard.block` ];
then
	mount /sdcard > /dev/null 2>&1;
	cp -f /tmp/recovery.log /sdcard/

else
	echo "No sdcard found!";
	exit 1;
fi;

exit 0;
	
