#!/sbin/sh

# Recovery Script to reformat Droid Incredible data partiton as /ext4
# 4/15/2011 by getitnowmarketing@gmail.com & savoxis@gmail.com
# using grep block as dinc has a yaffs2 /data/data partition also
# Modified 5/02/11 for thunderbolt/mecha GNM 
# Version 1.3


DMKE2FS="/sbin/mke2fs"
DTUNE2FS="/sbin/tune2fs"
DE2FSCK="/sbin/e2fsck"
MECHDATAPART="/dev/block/mmcblk0p26"
MECHSYSPART="/dev/block/mmcblk0p25"
CHECKMOUNTEDD=`mount | grep "$MECHDATAPART" | awk '{print $2}'`
CHECKMOUNTEDS=`mount | grep "$MECHSYSPART" | awk '{print $2}'` 



case $1 in
	check)
	 if [ "$CHECKMOUNTEDD" == "on" ]; then
		echo "/data already mounted"
	 else
		mount /data 2>/dev/null
		sleep 2
	 fi
 	
	if [ "$CHECKMOUNTEDS" == "on" ]; then
		echo "/system already mounted"
	 else
		mount /system 2>/dev/null
		sleep 2
	 fi	
		
		  #Grab 5th collumn from the mount output greping only line with data
		FSTYPE=`mount | grep "$MECHDATAPART" | awk '{print $5}'` 
		echo "Filesystem for Data is: $FSTYPE"
		
		FSTYPES=`mount | grep "$MECHSYSPART" | awk '{print $5}'` 
		echo "Filesystem for System is: $FSTYPES"
	 ;;
        formatext4)
	  if [ "$CHECKMOUNTEDD" == "on" ]; then
	  	echo "/data already mounted"
	  else
		echo "mounting /data to check fs type"
		mount /data 2>/dev/null
		sleep 2
	  fi
          FSTYPE=`mount | grep "$MECHDATAPART" | awk '{print $5}'` 

	  if [ "$CHECKMOUNTEDS" == "on" ]; then
		echo "/system already mounted"
	  else
		mount /system 2>/dev/null
		sleep 2
	  fi
	  FSTYPES=`mount | grep "$MECHSYSPART" | awk '{print $5}'`
  
		#Check if FS is ext4 already
	  if [ "$FSTYPE" == "ext4" ]; then
		echo "your /data filesystem is already ext4"
		exit 1
	  fi

	  if [ "$FSTYPES" == "ext4" ]; then
		echo "your /system filesystem is already ext4"
		exit 1
	  fi

	    #Check if FS is ext3
	  if [ "$FSTYPE" == "ext3" ]; then
		echo "/data is ext3 ..proceed"
	  else
		echo "/data filesystem is $FSTYPE"
		   exit 1			 
	  fi

	    #Check if FS is ext3
	  if [ "$FSTYPES" == "ext3" ]; then
		echo "/system is ext3 ..proceed"
	  else
		echo "/system filesystem is $FSTYPE"
		   exit 1			 
	  fi
		 
		echo "unmounting /data"
		umount /data 2>/dev/null
		sleep 2

		echo "unmounting /system"
		umount /system 2>/dev/null
		sleep 2
	 
		"$DTUNE2FS" -O extents,uninit_bg,dir_index "$MECHDATAPART"
		"$DE2FSCK" -fpDC0 "$MECHDATAPART"
		sleep 2
		echo "/data done"

		"$DTUNE2FS" -O extents,uninit_bg,dir_index "$MECHSYSPART"
		"$DE2FSCK" -fpDC0 "$MECHSYSPART"
		sleep 2
		echo "/system done"	
	 ;;


	reformatext3)
	  if [ "$CHECKMOUNTEDD" == "on" ]; then
	  	echo "/data already mounted"
	  else
		echo "mounting /data to check fs type"
		mount /data 2>/dev/null
		sleep 2
	  fi
          FSTYPE=`mount | grep "$MECHDATAPART" | awk '{print $5}'` 

	  if [ "$CHECKMOUNTEDS" == "on" ]; then
		echo "/system already mounted"
	  else
		mount /system 2>/dev/null
		sleep 2
	  fi
	  FSTYPES=`mount | grep "$MECHSYSPART" | awk '{print $5}'`

	  if [ "$FSTYPE" == "ext4" ]; then
		echo "/data is ext4 ..proceed"
		
	  else 
		echo "/data is not currently ext4"
		exit 1
	  fi

	  if [ "$FSTYPES" == "ext4" ]; then
		echo "/system is ext4 ..proceed"
		
	  else 
		echo "/system is not currently ext4"
		exit 1
	  fi
		
		echo "unmounting /data"
		umount /data 2>/dev/null
		sleep 2
		echo "preparing to repartition /data as ext3"
		"$DMKE2FS" -t ext3 "$MECHDATAPART"
		"$DE2FSCK" -fp "$MECHDATAPART"
		sleep 2

		echo "unmounting /system"
		umount /system 2>/dev/null
		sleep 2
		echo "preparing to repartition /system as ext3"
		"$DMKE2FS" -t ext3 "$MECHSYSPART"
		"$DE2FSCK" -fp "$MECHSYSPART"
		sleep 2
	 ;;
	--)
	 ;;
esac
	CHECKMOUNTEDD=`mount | grep "$MECHDATAPART" | awk '{print $2}'` 
	if [ "$CHECKMOUNTEDD" == "on" ]; then
		echo "unmounting /data"
		umount /data 2>/dev/null
		sleep 2
	fi
	CHECKMOUNTEDS=`mount | grep "$MECHSYSPART" | awk '{print $2}'` 
	if [ "$CHECKMOUNTEDS" == "on" ]; then
		echo "unmounting /system"
		umount /system 2>/dev/null
		sleep 2
		exit 0
	else
		exit 0
        fi
