#!/sbin/sh

GETPROP="/sbin/getprop"

if [ `$GETPROP ro.ums.path` == "" ]; then
	echo "Error detecting ums path!"
fi

echo "" > `$GETPROP ro.ums.path`

LIST=`mount | grep "^/" | grep "type yaffs*\|vfat\|ext*" | grep "system*\|data*\|sd-ext*\|sdcard*\|internal_sdcard*" | cut -d\  -f 3 | sort -rn`

if [ "$LIST" != "" ]; then
	for i in $LIST
	do
		echo "unmounting $i"		
		umount $i
			if [ $? != "0" ]; then
				echo "Unable to unmount $i !"
				exit 1
			fi

	done
fi

exit 0
