#!/sbin/sh

um
if [ $? != "0" ]; then
	echo "Unable to unmount!"
	exit 1
fi

chmod 0777 /sys/module/android/parameters/usb_mode
chmod 0777 /sys/devices/platform/msm_hsusb/gadget/lun0/file

case $1 in
    on)
	#echo 6308 > /sys/module/android/parameters/product_id
        echo /dev/block/mmcblk1p1 > /sys/devices/platform/msm_hsusb/gadget/lun0/file
	sleep 1
	
	echo mass_storage > /sys/module/android/parameters/usb_mode
	echo "USB Mass Storage enabled"

        ;;
    off)
	sync
	echo "" > /sys/devices/platform/msm_hsusb/gadget/lun0/file
	sleep 1
	echo internet_connection > /sys/module/android/parameters/usb_mode
	echo "USB Mass Storage disabled"
	;;
    internal)
	#echo 6308 > /sys/module/android/parameters/product_id
	echo /dev/block/mmcblk0p15 > /sys/devices/platform/msm_hsusb/gadget/lun0/file
	sleep 1
	
	echo mass_storage > /sys/module/android/parameters/usb_mode
	echo "USB Mass Storage enabled"  
	;;  
	--)
        ;;
esac

exit 0

