#!/sbin/sh

um
if [ $? != "0" ]; then
	echo "Unable to unmount!"
	exit 1
fi

case $1 in
    on)
	echo /dev/block/mmcblk1p1 > /sys/devices/platform/usb_mass_storage/lun0/file
	echo "USB Mass Storage enabled"
        ;;
    off)
	sync
	echo "" > /sys/devices/platform/usb_mass_storage/lun0/file
	echo "USB Mass Storage disabled"
	;;
    internal)
	echo /dev/block/mmcblk0p37 > /sys/devices/platform/usb_mass_storage/lun0/file
	echo "Internal USB Mass Storage enabled"
	;;
    --)
        ;;
esac

exit 0

